receivers:
  otlp:
    protocols:
      http:
exporters:
  logging:
    logLevel: info
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]
