version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: websmith
      POSTGRES_PASSWORD: websmith
      POSTGRES_DB: websmith
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  minio:
    image: bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '4566:9000'
    command: minio server /data
    volumes:
      - minio-data:/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
  otel-collector:
    image: otel/opentelemetry-collector:0.91.0
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./infra/otel/otel-config.yaml:/etc/otel-config.yaml:ro
    ports:
      - '4318:4318'
  prometheus:
    image: prom/prometheus:v2.49.0
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
volumes:
  postgres-data:
  redis-data:
  minio-data:
